# Generated by Django 2.0 on 2018-01-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('latlong', models.CharField(blank=True, max_length=225, null=True)),
                ('doorno', models.CharField(blank=True, max_length=225, null=True)),
                ('landmark', models.CharField(blank=True, max_length=225, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=225, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('agegroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('agegroup', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agegroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alertsources',
            fields=[
                ('alertsources_id', models.AutoField(primary_key=True, serialize=False)),
                ('alertsource', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertsources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerttype',
            fields=[
                ('alerttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('alerttype', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointmentbooking',
            fields=[
                ('appointmentbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=225, null=True)),
                ('macaddress', models.CharField(blank=True, max_length=225, null=True)),
                ('isnew', models.IntegerField(blank=True, null=True)),
                ('visittype', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointmentbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Availablefacilities',
            fields=[
                ('availablefacilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'availablefacilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookingsources',
            fields=[
                ('bookingsources_id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcename', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookingsources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businessregtype',
            fields=[
                ('businessregtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('businessregtype', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'businessregtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=225)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicianMemberships',
            fields=[
                ('clinician_memberships_id', models.AutoField(primary_key=True, serialize=False)),
                ('association', models.CharField(blank=True, max_length=225, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinician_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinicians',
            fields=[
                ('clinicians_id', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'clinicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansDates',
            fields=[
                ('clinicians_dates_id', models.AutoField(primary_key=True, serialize=False)),
                ('alldays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansEducation',
            fields=[
                ('clinicians_education_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrationno', models.CharField(blank=True, max_length=225, null=True)),
                ('college', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'clinicians_education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansExperience',
            fields=[
                ('clinicians_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=225, null=True)),
                ('workfrom', models.DateField(blank=True, null=True)),
                ('workto', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansSpeciality',
            fields=[
                ('clinicians_speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('conditions_id', models.AutoField(primary_key=True, serialize=False)),
                ('conditionname', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Couponaccept',
            fields=[
                ('couponaccept_id', models.AutoField(primary_key=True, serialize=False)),
                ('couponaccept', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'couponaccept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupons_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.CharField(blank=True, max_length=225, null=True)),
                ('applicablesponsor', models.IntegerField(blank=True, null=True)),
                ('uniquecode', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('timevalidity', models.IntegerField(blank=True, null=True)),
                ('couponstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountcard',
            fields=[
                ('discountcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('discountcard', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('eligibility', models.IntegerField(blank=True, null=True)),
                ('familyrestriction', models.IntegerField(blank=True, null=True)),
                ('addfamilyrestriction', models.IntegerField(blank=True, null=True)),
                ('applicablesponser', models.IntegerField(blank=True, null=True)),
                ('otherbenfits', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'discountcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountcardFamily',
            fields=[
                ('discountcard_family_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discountcard_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountcardFamilyExtra',
            fields=[
                ('discountcard_family_extra_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discountcard_family_extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitiesServices',
            fields=[
                ('facilities_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities_services', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('from_2', models.CharField(blank=True, max_length=225, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('feedbackstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheckbooking',
            fields=[
                ('healthcheckbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthcheckbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthchecks',
            fields=[
                ('healthchecks_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthcheck', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('promoimage', models.CharField(blank=True, max_length=225, null=True)),
                ('applicable_sponser', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthchecks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthchecksInclusion',
            fields=[
                ('healthchecks_inclusion_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'healthchecks_inclusion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthproviders',
            fields=[
                ('healthproviders_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_branch', models.IntegerField(blank=True, null=True)),
                ('under_healthproviders_id', models.IntegerField(blank=True, null=True)),
                ('display_cost', models.IntegerField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('m_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthproviders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthprovidersSpeciality',
            fields=[
                ('healthproviders_speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('speciality_name', models.CharField(blank=True, max_length=225, null=True)),
                ('speciality_description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discountpercentage', models.IntegerField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthproviders_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthrecords',
            fields=[
                ('healthrecords_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthrecord', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthseeker',
            fields=[
                ('healthseeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('underfamily', models.IntegerField(blank=True, null=True)),
                ('undersponser', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'healthseeker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerAlerts',
            fields=[
                ('healthseeker_alerts_id', models.AutoField(primary_key=True, serialize=False)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('alert_to', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthseeker_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerAvailabilities',
            fields=[
                ('healthseeker_availabilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthseeker_availabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerHealthrecords',
            fields=[
                ('healthseeker_healthrecords_id', models.AutoField(primary_key=True, serialize=False)),
                ('refdate', models.DateField(blank=True, null=True)),
                ('file_2', models.CharField(blank=True, max_length=225, null=True)),
                ('file3', models.CharField(blank=True, max_length=225, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('m_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthseeker_healthrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerType',
            fields=[
                ('healthseeker_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthseeker_type', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'healthseeker_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photoalbum',
            fields=[
                ('photoalbum_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_title', models.CharField(blank=True, max_length=225, null=True)),
                ('image_path', models.CharField(max_length=225)),
                ('forusage', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photoalbum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plans_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofpatients', models.IntegerField(blank=True, null=True)),
                ('benefits', models.CharField(blank=True, max_length=225, null=True)),
                ('share1stconsultation', models.IntegerField(blank=True, null=True)),
                ('sharenextconsultation', models.IntegerField(blank=True, null=True)),
                ('planworks', models.CharField(blank=True, max_length=225, null=True)),
                ('addbenfits', models.CharField(blank=True, max_length=225, null=True)),
                ('cmslicencevalidity', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.CharField(blank=True, max_length=225, null=True)),
                ('discount1stconsultation', models.IntegerField(blank=True, null=True)),
                ('discountnextconsultation', models.IntegerField(blank=True, null=True)),
                ('promoimage', models.CharField(blank=True, max_length=225, null=True)),
                ('applicability', models.CharField(blank=True, max_length=225, null=True)),
                ('doctorscoupon', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansGroups',
            fields=[
                ('plans_groups_id', models.AutoField(primary_key=True, serialize=False)),
                ('plans_group', models.CharField(blank=True, max_length=225, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plans_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansGroupsSpecialities',
            fields=[
                ('plans_groups_specialities_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'plans_groups_specialities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priyority',
            fields=[
                ('priyority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priyority', models.IntegerField(blank=True, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'priyority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('poorofession', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrels',
            fields=[
                ('referrels_id', models.AutoField(primary_key=True, serialize=False)),
                ('fromusers_id', models.IntegerField(blank=True, null=True)),
                ('referredusers_id', models.IntegerField(blank=True, null=True)),
                ('cashback', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrelscheme',
            fields=[
                ('referrelscheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('noofreferels', models.IntegerField(blank=True, null=True)),
                ('cashback', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrelscheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationWelcomeMessage',
            fields=[
                ('registration_welcome_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_welcome_message', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('m_user', models.IntegerField(blank=True, null=True)),
                ('c_user', models.IntegerField(blank=True, null=True)),
                ('m_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_welcome_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resellerpackages',
            fields=[
                ('resellerpackages_id', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofdiscountcards', models.IntegerField(blank=True, null=True)),
                ('packagetype', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('campaignvalidfrom', models.DateField(blank=True, null=True)),
                ('campaignvalidto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resellerpackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('resellers_id', models.AutoField(primary_key=True, serialize=False)),
                ('fathername', models.CharField(blank=True, max_length=225, null=True)),
                ('relationofsalesagents', models.CharField(blank=True, max_length=225, null=True)),
                ('idproof', models.CharField(blank=True, max_length=225, null=True)),
                ('serviceoffered', models.CharField(blank=True, max_length=225, null=True)),
                ('seviceagreementimage', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'resellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=225)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
                ('roleocode', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesagentpackages',
            fields=[
                ('salesagentpackages_id', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofdiscountcards', models.IntegerField(blank=True, null=True)),
                ('packagetype', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('campaignvalidfrom', models.DateField(blank=True, null=True)),
                ('campaignvalidto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salesagentpackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesagents',
            fields=[
                ('salesagents_id', models.AutoField(primary_key=True, serialize=False)),
                ('agencyname', models.CharField(blank=True, max_length=225, null=True)),
                ('registrationdate', models.DateField(blank=True, null=True)),
                ('registrationno', models.IntegerField(blank=True, null=True)),
                ('registrationproof', models.CharField(blank=True, max_length=225, null=True)),
                ('authorizedpersonproof', models.CharField(blank=True, max_length=225, null=True)),
                ('serviceoffered', models.CharField(blank=True, max_length=225, null=True)),
                ('minimumnoresellers', models.IntegerField(blank=True, null=True)),
                ('serviceproposal', models.CharField(blank=True, max_length=225, null=True)),
                ('ndaagreemert', models.IntegerField(blank=True, null=True)),
                ('ndaagreementproof', models.CharField(blank=True, max_length=225, null=True)),
                ('agreementstarts', models.DateField(blank=True, null=True)),
                ('agreementends', models.DateField(blank=True, null=True)),
                ('serviceagreementimage', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'salesagents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salestarget',
            fields=[
                ('salestarget_id', models.AutoField(primary_key=True, serialize=False)),
                ('salestarget', models.CharField(blank=True, max_length=225, null=True)),
                ('noofsales', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('addextracards', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salestarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretquestions',
            fields=[
                ('secretquestions_id', models.AutoField(primary_key=True, serialize=False)),
                ('secretquestion', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secretquestions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialityType',
            fields=[
                ('speciality_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_type_name', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speciality_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsors_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(blank=True, max_length=225, null=True)),
                ('groupsize', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
                ('operatinghours', models.CharField(blank=True, max_length=225, null=True)),
                ('oprtainglocation', models.CharField(blank=True, max_length=225, null=True)),
                ('website', models.CharField(blank=True, max_length=225, null=True)),
                ('requiredlocation', models.CharField(blank=True, max_length=225, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sponsors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorsGroup',
            fields=[
                ('sponsors_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('sponsors_group', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sponsors_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptoms_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'symptoms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('telephone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telephone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('test_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_category', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('testimonials_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
                ('video', models.CharField(blank=True, max_length=225, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testimonials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestSubcategory',
            fields=[
                ('test_subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('timeslots_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeslots', models.CharField(blank=True, max_length=225, null=True)),
                ('fromslot', models.TimeField(blank=True, null=True)),
                ('toslot', models.TimeField(blank=True, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnAppointmentbookings',
            fields=[
                ('trxn_appointmentbookings_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentbooking_date', models.DateField()),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('session_activity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_appointmentbookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnCoupons',
            fields=[
                ('trxn_coupons_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnDiscountcard',
            fields=[
                ('trxn_discountcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_discountcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnHealthcheckbooking',
            fields=[
                ('trxn_healthcheckbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_healthcheckbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnPayments',
            fields=[
                ('trxn_payments_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('paymentfor', models.CharField(blank=True, max_length=225, null=True)),
                ('for_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=225)),
                ('firstname', models.CharField(blank=True, max_length=225, null=True)),
                ('lastname', models.CharField(blank=True, max_length=225, null=True)),
                ('middlename', models.CharField(blank=True, max_length=225, null=True)),
                ('enc_password', models.CharField(max_length=225)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('pw_request', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('reg_by', models.IntegerField(blank=True, null=True)),
                ('m_date', models.DateTimeField(blank=True, null=True)),
                ('m_by', models.IntegerField(blank=True, null=True)),
                ('failure_attempts', models.IntegerField(blank=True, null=True)),
                ('secretanswer', models.CharField(blank=True, max_length=225, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=225, null=True)),
                ('macaddress', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wellnessplan',
            fields=[
                ('wellnessplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicalhistory', models.CharField(blank=True, max_length=225, null=True)),
                ('surgicalhistory', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'wellnessplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessplanProfession',
            fields=[
                ('wellnessplan_profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('wellnessplan_profession', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellnessplan_profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessplanSocialhistory',
            fields=[
                ('wellnessplan_socialhistory_id', models.AutoField(primary_key=True, serialize=False)),
                ('wellnessplan_socialhistory', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellnessplan_socialhistory',
                'managed': False,
            },
        ),
    ]
