# Generated by Django 2.0 on 2018-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('latlong', models.CharField(blank=True, max_length=225, null=True)),
                ('doorno', models.CharField(blank=True, max_length=225, null=True)),
                ('landmark', models.CharField(blank=True, max_length=225, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=225, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('agegroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('agegroup', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agegroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alertsources',
            fields=[
                ('alertsources_id', models.AutoField(primary_key=True, serialize=False)),
                ('alertsource', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertsources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerttype',
            fields=[
                ('alerttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('alerttype', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointmentbooking',
            fields=[
                ('appointmentbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointmentbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Availablefacilities',
            fields=[
                ('availablefacilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'availablefacilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookingsources',
            fields=[
                ('bookingsources_id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcename', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookingsources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businessregtype',
            fields=[
                ('businessregtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('businessregtype', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'businessregtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=225)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicianMemberships',
            fields=[
                ('clinician_memberships_id', models.AutoField(primary_key=True, serialize=False)),
                ('association', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'clinician_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinicians',
            fields=[
                ('clinicians_id', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'clinicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansDates',
            fields=[
                ('clinicians_dates_id', models.AutoField(primary_key=True, serialize=False)),
                ('alldays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansEducation',
            fields=[
                ('clinicians_education_id', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CliniciansExperience',
            fields=[
                ('clinicians_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=225, null=True)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('workfrom', models.DateField(blank=True, null=True)),
                ('workto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('conditions_id', models.AutoField(primary_key=True, serialize=False)),
                ('conditionname', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Couponaccept',
            fields=[
                ('couponaccept_id', models.AutoField(primary_key=True, serialize=False)),
                ('couponaccept', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'couponaccept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupons_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.CharField(blank=True, max_length=225, null=True)),
                ('applicablesponsor', models.IntegerField(blank=True, null=True)),
                ('uniquecode', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('timevalidity', models.IntegerField(blank=True, null=True)),
                ('couponstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountcard',
            fields=[
                ('discountcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('discountcard', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('eligibility', models.IntegerField(blank=True, null=True)),
                ('familyrestriction', models.IntegerField(blank=True, null=True)),
                ('addfamilyrestriction', models.IntegerField(blank=True, null=True)),
                ('applicablesponser', models.IntegerField(blank=True, null=True)),
                ('otherbenfits', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'discountcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountcardFamily',
            fields=[
                ('discountcard_family_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discountcard_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountcardFamilyExtra',
            fields=[
                ('discountcard_family_extra_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discountcard_family_extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitiesServices',
            fields=[
                ('facilities_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities_services', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('from_2', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheckbookibg',
            fields=[
                ('healthcheckbookibg_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthcheckbookibg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthchecks',
            fields=[
                ('healthchecks_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthcheck', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('promoimage', models.CharField(blank=True, max_length=225, null=True)),
                ('applicable_sponser', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthchecks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthchecksInclusion',
            fields=[
                ('healthchecks_inclusion_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'healthchecks_inclusion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthproviders',
            fields=[
                ('healthproviders_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_branch', models.IntegerField(blank=True, null=True)),
                ('under_healthproviders_id', models.IntegerField(blank=True, null=True)),
                ('display_cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthproviders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthrecords',
            fields=[
                ('healthrecords_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthrecord', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthseeker',
            fields=[
                ('healthseeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('underfamily', models.IntegerField(blank=True, null=True)),
                ('undersponser', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'healthseeker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerAvailabilities',
            fields=[
                ('healthseeker_availabilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthseeker_availabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerHealthrecords',
            fields=[
                ('healthseeker_healthrecords_id', models.AutoField(primary_key=True, serialize=False)),
                ('refdate', models.DateField(blank=True, null=True)),
                ('file_2', models.CharField(blank=True, max_length=225, null=True)),
                ('file3', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'healthseeker_healthrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photoalbum',
            fields=[
                ('photoalbum_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_title', models.CharField(blank=True, max_length=225, null=True)),
                ('image_path', models.CharField(max_length=225)),
                ('forusage', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photoalbum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plans_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofpatients', models.IntegerField(blank=True, null=True)),
                ('benefits', models.CharField(blank=True, max_length=225, null=True)),
                ('share1stconsultation', models.IntegerField(blank=True, null=True)),
                ('sharenextconsultation', models.IntegerField(blank=True, null=True)),
                ('planworks', models.CharField(blank=True, max_length=225, null=True)),
                ('addbenfits', models.CharField(blank=True, max_length=225, null=True)),
                ('cmslicencevalidity', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.CharField(blank=True, max_length=225, null=True)),
                ('discount1stconsultation', models.IntegerField(blank=True, null=True)),
                ('discountnextconsultation', models.IntegerField(blank=True, null=True)),
                ('promoimage', models.CharField(blank=True, max_length=225, null=True)),
                ('applicability', models.CharField(blank=True, max_length=225, null=True)),
                ('doctorscoupon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansGroups',
            fields=[
                ('plans_groups_id', models.AutoField(primary_key=True, serialize=False)),
                ('plans_group', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'plans_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansGroupsSpecialities',
            fields=[
                ('plans_groups_specialities_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'plans_groups_specialities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('poorofession', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrelscheme',
            fields=[
                ('referrelscheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('noofreferels', models.IntegerField(blank=True, null=True)),
                ('cashback', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrelscheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationWelcomeMessage',
            fields=[
                ('registration_welcome_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_welcome_message', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_welcome_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resellerpackages',
            fields=[
                ('resellerpackages_id', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofdiscountcards', models.IntegerField(blank=True, null=True)),
                ('packagetype', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('campaignvalidfrom', models.DateField(blank=True, null=True)),
                ('campaignvalidto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resellerpackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('resellers_id', models.AutoField(primary_key=True, serialize=False)),
                ('fathername', models.CharField(blank=True, max_length=225, null=True)),
                ('relationofsalesagents', models.CharField(blank=True, max_length=225, null=True)),
                ('idproof', models.CharField(blank=True, max_length=225, null=True)),
                ('serviceoffered', models.CharField(blank=True, max_length=225, null=True)),
                ('seviceagreementimage', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'resellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=225)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesagentpackages',
            fields=[
                ('salesagentpackages_id', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('noofdiscountcards', models.IntegerField(blank=True, null=True)),
                ('packagetype', models.CharField(blank=True, max_length=225, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('campaignvalidfrom', models.DateField(blank=True, null=True)),
                ('campaignvalidto', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salesagentpackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesagents',
            fields=[
                ('salesagents_id', models.AutoField(primary_key=True, serialize=False)),
                ('agencyname', models.CharField(blank=True, max_length=225, null=True)),
                ('registrationdate', models.DateField(blank=True, null=True)),
                ('registrationno', models.IntegerField(blank=True, null=True)),
                ('registrationproof', models.CharField(blank=True, max_length=225, null=True)),
                ('authorizedpersonproof', models.CharField(blank=True, max_length=225, null=True)),
                ('serviceoffered', models.CharField(blank=True, max_length=225, null=True)),
                ('minimumnoresellers', models.IntegerField(blank=True, null=True)),
                ('serviceproposal', models.CharField(blank=True, max_length=225, null=True)),
                ('ndaagreemert', models.IntegerField(blank=True, null=True)),
                ('ndaagreementproof', models.CharField(blank=True, max_length=225, null=True)),
                ('agreementstarts', models.DateField(blank=True, null=True)),
                ('agreementends', models.DateField(blank=True, null=True)),
                ('serviceagreementimage', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'salesagents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salestarget',
            fields=[
                ('salestarget_id', models.AutoField(primary_key=True, serialize=False)),
                ('salestarget', models.CharField(blank=True, max_length=225, null=True)),
                ('noofsales', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('addextracards', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salestarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsors_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(blank=True, max_length=225, null=True)),
                ('groupsize', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
                ('operatinghours', models.CharField(blank=True, max_length=225, null=True)),
                ('oprtainglocation', models.CharField(blank=True, max_length=225, null=True)),
                ('requiredlocation', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'sponsors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorsGroup',
            fields=[
                ('sponsors_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('sponsors_group', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sponsors_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subrole',
            fields=[
                ('subrole_id', models.AutoField(primary_key=True, serialize=False)),
                ('subrole', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptoms_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'symptoms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('telephone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone1', models.IntegerField(blank=True, null=True)),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('phone3', models.IntegerField(blank=True, null=True)),
                ('phone4', models.IntegerField(blank=True, null=True)),
                ('phone5', models.IntegerField(blank=True, null=True)),
                ('phone6', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telephone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('test_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_category', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('testimonials_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
                ('video', models.CharField(blank=True, max_length=225, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testimonials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestSubcategory',
            fields=[
                ('test_subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'test_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('timeslots_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeslots', models.CharField(blank=True, max_length=225, null=True)),
                ('fromslot', models.TimeField(blank=True, null=True)),
                ('toslot', models.TimeField(blank=True, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=225)),
                ('firstname', models.CharField(blank=True, max_length=225, null=True)),
                ('lastname', models.CharField(blank=True, max_length=225, null=True)),
                ('middlename', models.CharField(blank=True, max_length=225, null=True)),
                ('enc_password', models.CharField(max_length=225)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('pw_request', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wellnessplan',
            fields=[
                ('wellnessplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicalhistory', models.CharField(blank=True, max_length=225, null=True)),
                ('surgicalhistory', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'wellnessplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessplanProfession',
            fields=[
                ('wellnessplan_profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('wellnessplan_profession', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellnessplan_profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessplanSocialhistory',
            fields=[
                ('wellnessplan_socialhistory_id', models.AutoField(primary_key=True, serialize=False)),
                ('wellnessplan_socialhistory', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellnessplan_socialhistory',
                'managed': False,
            },
        ),
    ]
