# Generated by Django 2.0 on 2018-01-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliniciansSpeciality',
            fields=[
                ('clinicians_speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicians_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheckbooking',
            fields=[
                ('healthcheckbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthcheckbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthprovidersSpeciality',
            fields=[
                ('healthproviders_speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('speciality_name', models.CharField(blank=True, max_length=225, null=True)),
                ('speciality_description', models.CharField(blank=True, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discountpercentage', models.IntegerField(blank=True, null=True)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthproviders_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerAlerts',
            fields=[
                ('healthseeker_alerts_id', models.AutoField(primary_key=True, serialize=False)),
                ('activefrom', models.DateTimeField(blank=True, null=True)),
                ('activeto', models.DateTimeField(blank=True, null=True)),
                ('alert_to', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healthseeker_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthseekerType',
            fields=[
                ('healthseeker_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('healthseeker_type', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'healthseeker_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priyority',
            fields=[
                ('priyority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priyority', models.IntegerField(blank=True, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'priyority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrels',
            fields=[
                ('referrels_id', models.AutoField(primary_key=True, serialize=False)),
                ('fromusers_id', models.IntegerField(blank=True, null=True)),
                ('referredusers_id', models.IntegerField(blank=True, null=True)),
                ('cashback', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretquestions',
            fields=[
                ('secretquestions_id', models.AutoField(primary_key=True, serialize=False)),
                ('secretquestion', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secretquestions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialityType',
            fields=[
                ('speciality_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_type_name', models.CharField(blank=True, max_length=225, null=True)),
                ('sort_by', models.IntegerField(blank=True, null=True)),
                ('status_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speciality_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnAppointmentbookings',
            fields=[
                ('trxn_appointmentbookings_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentbooking_date', models.DateField()),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('session_activity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_appointmentbookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnCoupons',
            fields=[
                ('trxn_coupons_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnDiscountcard',
            fields=[
                ('trxn_discountcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_discountcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnHealthcheckbooking',
            fields=[
                ('trxn_healthcheckbooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('sessionactivity', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_healthcheckbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrxnPayments',
            fields=[
                ('trxn_payments_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status_2', models.CharField(blank=True, max_length=225, null=True)),
                ('paymentfor', models.CharField(blank=True, max_length=225, null=True)),
                ('for_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=225, null=True)),
                ('trxn_by', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trxn_payments',
                'managed': False,
            },
        ),
    ]
