# Generated by Django 2.0 on 2018-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180213_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_IP',
            field=models.GenericIPAddressField(default='127.0.0.1', editable=False),
        ),
    ]
