# Generated by Django 2.0 on 2018-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180213_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
