# Generated by Django 2.0 on 2018-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180213_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
