# Generated by Django 2.0 on 2018-02-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180207_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptoms',
            options={'managed': True},
        ),
    ]
