# Generated by Django 2.0 on 2018-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180216_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=40),
        ),
        migrations.AddField(
            model_name='seeker',
            name='appointments',
            field=models.ManyToManyField(to='api.Appointment'),
        ),
    ]
