# Generated by Django 2.0 on 2018-02-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180212_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniciansspeciality',
            options={'managed': False},
        ),
    ]
