# Generated by Django 2.0 on 2018-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180217_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled')], default='pending', max_length=40),
        ),
    ]
