# Generated by Django 2.0 on 2018-02-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180212_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicians',
            options={'managed': True},
        ),
    ]
