# Generated by Django 2.0 on 2018-02-18 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180217_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='break_timings',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=2), blank=True, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='vacations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=2), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='work_timings',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=2), blank=True, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='appointments',
            field=models.ManyToManyField(editable=False, to='api.Appointment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
