# Generated by Django 2.0 on 2018-02-25 09:56

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180218_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'blog_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(default=api.models.current_timestamp, editable=False)),
            ],
            options={
                'db_table': 'blog_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CDN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cdn')),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=api.models.current_timestamp, editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default_blog.jpg', upload_to='blog')),
                ('url', models.URLField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_added', models.DateTimeField(default=api.models.current_timestamp, editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BlogCategory')),
            ],
            options={
                'db_table': 'posts',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('healthprovider', 'healthprovider'), ('healthseeker', 'healthseeker'), ('clinician', 'clinician'), ('sponsor', 'sponsor'), ('salesagent', 'salesagent'), ('reseller', 'reseller'), ('editor', 'editor'), ('admin', 'admin')], editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
    ]
