# Generated by Django 2.0 on 2018-02-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='featured_posts',
            field=models.ManyToManyField(blank=True, null=True, to='api.Post'),
        ),
        migrations.AlterField(
            model_name='cdn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cdn'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clicks',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
