# Generated by Django 2.0 on 2018-02-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='featured_posts',
            field=models.ManyToManyField(blank=True, null=True, to='api.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clicks',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
