# Generated by Django 2.0 on 2018-02-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180228_2355'),
        ('api', '0016_auto_20180228_2226'),
    ]

    operations = [
    ]
