# Generated by Django 2.0 on 2018-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180301_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
