# Generated by Django 2.0 on 2018-03-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180310_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Organization'),
            preserve_default=False,
        ),
    ]
