# Generated by Django 2.0 on 2018-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180310_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('healthprovider', 'healthprovider'), ('healthseeker', 'healthseeker'), ('clinician', 'clinician'), ('sponsor', 'sponsor'), ('poc', 'poc'), ('salesagent', 'salesagent'), ('reseller', 'reseller'), ('editor', 'editor'), ('admin', 'admin')], editable=False, max_length=30),
        ),
    ]
