# Generated by Django 2.0 on 2018-03-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180311_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='validty',
            new_name='validity',
        ),
    ]
