# Generated by Django 2.0 on 2018-03-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180311_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcheckup',
            old_name='title',
            new_name='name',
        ),
    ]
