# Generated by Django 2.0 on 2018-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180311_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='healthchecks',
            field=models.ManyToManyField(blank=True, null=True, to='api.HealthCheckup'),
        ),
    ]
