# Generated by Django 2.0 on 2018-03-18 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_seeker_healthchecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='vacations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=2), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('telugu', 'telugu'), ('marathi', 'marathi'), ('malayalam', 'malayalam'), ('gujarati', 'gujarati'), ('bhojpuri', 'bhojpuri'), ('tamil', 'tamil'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='profession',
            field=models.CharField(choices=[('doctor', 'doctor'), ('teacher', 'teacher'), ('engineer', 'engineer'), ('professor', 'professor'), ('business', 'business'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1),
        ),
    ]
