# Generated by Django 2.0 on 2018-03-21 08:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180318_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_modified',
            field=models.DateTimeField(default=api.models.current_timestamp),
        ),
        migrations.AddField(
            model_name='appointment',
            name='from_timestamp',
            field=models.DateTimeField(default=api.models.current_timestamp),
        ),
        migrations.AddField(
            model_name='appointment',
            name='to_timestamp',
            field=models.DateTimeField(default=api.models.current_timestamp),
        ),
    ]
