# Generated by Django 2.0 on 2018-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180318_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_education',
            field=models.CharField(choices=[('10', '10'), ('10+2', '10+2')], default='10', editable=False, max_length=30),
        ),
    ]
