# Generated by Django 2.0 on 2018-03-21 08:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180321_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='create_on',
            field=models.DateTimeField(default=api.models.current_timestamp, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_modified',
            field=models.DateTimeField(default=api.models.current_timestamp, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='from_timestamp',
            field=models.DateTimeField(default=api.models.current_timestamp, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='to_timestamp',
            field=models.DateTimeField(default=api.models.current_timestamp, editable=False),
        ),
    ]
