# Generated by Django 2.0 on 2018-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_basic_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diploma',
            field=models.CharField(choices=[('none', 'none'), ('diploma', 'diploma'), ('diplomalist', 'diplomalist')], default='none', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='post_graduate',
            field=models.CharField(choices=[('none', 'none'), ('pg', 'pg'), ('pglist', 'pglist')], default='none', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='super_speciality',
            field=models.CharField(choices=[('none', 'none'), ('super_speciality1', 'super_speciality1'), ('super_speciality2', 'super_speciality2')], default='none', editable=False, max_length=30),
        ),
    ]
