# Generated by Django 2.0 on 2018-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180320_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_degrees',
            field=models.TextField(default='TEST1'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_trainings',
            field=models.TextField(default='TEST'),
        ),
    ]
