# Generated by Django 2.0 on 2018-03-20 20:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180320_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinician',
            name='awards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='clinician',
            name='conditions_treated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='clinician',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinician',
            name='discount_sub',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinician',
            name='fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinician',
            name='offerings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='clinician',
            name='procedures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='basic_education',
            field=models.CharField(choices=[('10', '10'), ('10+2', '10+2')], default='10', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='diploma',
            field=models.CharField(choices=[('none', 'none'), ('diploma', 'diploma'), ('diplomalist', 'diplomalist')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_graduate',
            field=models.CharField(choices=[('none', 'none'), ('pg', 'pg'), ('pglist', 'pglist')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='super_speciality',
            field=models.CharField(choices=[('none', 'none'), ('super_speciality1', 'super_speciality1'), ('super_speciality2', 'super_speciality2')], default='none', max_length=30),
        ),
    ]
