# Generated by Django 2.0 on 2018-03-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_appointment_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Appointment')),
                ('css_class', models.CharField(blank=True, choices=[('event-info', 'Info'), ('event-success', 'Success'), ('event-warning', 'Warning'), ('event-special', 'Special')], max_length=20, verbose_name='CSS Class')),
            ],
            bases=('api.appointment',),
        ),
    ]
