# Generated by Django 2.0 on 2018-03-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180322_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='css_class',
            field=models.CharField(choices=[('event-info', 'Info'), ('event-success', 'Success'), ('event-warning', 'Warning'), ('event-special', 'Special')], default='event-info', editable=False, max_length=20),
        ),
    ]
