# Generated by Django 2.0 on 2018-03-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_appointment_css_class'),
        ('api', '0034_auto_20180321_0134'),
    ]

    operations = [
    ]
