# Generated by Django 2.0 on 2018-03-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180326_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='parent_provider',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='poc',
        ),
    ]
