# Generated by Django 2.0 on 2018-03-28 14:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180328_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active_from',
            field=models.DateField(default=api.models.current_timestamp),
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
        migrations.AddField(
            model_name='provider',
            name='parent_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('clinic', 'clinic'), ('hospital', 'hospital'), ('diagnostic_centre', 'diagnostic center')], default='hospital', max_length=30),
        ),
    ]
