# Generated by Django 2.0 on 2018-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180328_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(default='Default Speciality Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=models.CharField(default='Default Name', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
