# Generated by Django 2.0 on 2018-03-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180328_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialities',
        ),
    ]
