# Generated by Django 2.0 on 2018-03-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180401_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
