# Generated by Django 2.0 on 2018-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='specialities',
            field=models.ManyToManyField(to='api.Speciality'),
        ),
        migrations.AddField(
            model_name='provider',
            name='specialities',
            field=models.ManyToManyField(to='api.Speciality'),
        ),
    ]
