# Generated by Django 2.0 on 2018-04-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180329_1827'),
        ('api', '0048_auto_20180401_0407'),
    ]

    operations = [
    ]
