# Generated by Django 2.0 on 2018-04-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20180407_1803'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='seeker',
            name='family',
        ),
        migrations.AddField(
            model_name='seeker',
            name='family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family', to='api.User'),
        ),

    ]
