# Generated by Django 2.0 on 2018-04-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20180407_2032'),
    ]

    operations = [


        migrations.AlterField(
            model_name='seeker',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family', to='api.User'),
        ),

    ]
