# Generated by Django 2.0 on 2018-04-09 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180407_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),

        migrations.RemoveField(
            model_name='seeker',
            name='language',
        ),
   
        migrations.AddField(
            model_name='seeker',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='api.Languages'),
        ),
    ]
