# Generated by Django 2.0 on 2018-04-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180411_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='extra',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
