# Generated by Django 2.0 on 2018-04-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20180411_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='conditions_treated',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='discount_sub',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='education',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='memberships',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='offerings',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='registrations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='basic_education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diploma',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_degrees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_trainings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_graduate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='super_speciality',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
