# Generated by Django 2.0 on 2018-04-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20180412_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinician',
            name='first_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
