# Generated by Django 2.0 on 2018-04-12 08:46

import api.models
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180412_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='awards',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['name', 'description', 'year', 'recognised_by'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='discount_offerings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.Clinician.get_def_discount, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['name', 'amount', 'type', 'description'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='education',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['year', 'title', 'description', 'type'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='experience_training',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['year', 'position', 'description', 'type'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='memberships',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['name', 'country', 'city'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='procedure_conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['name', 'description', 'type', 'date'])])),
        ),
        migrations.AddField(
            model_name='clinician',
            name='registrations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField(validators=[django.contrib.postgres.validators.KeysValidator(['name', 'reg_no', 'year'])])),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
