# Generated by Django 2.0 on 2018-04-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180412_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('telugu', 'telugu'), ('marathi', 'marathi'), ('malayalam', 'malayalam'), ('gujarati', 'gujarati'), ('bhojpuri', 'bhojpuri'), ('tamil', 'tamil'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
