# Generated by Django 2.0 on 2018-04-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20180416_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='language',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
