# Generated by Django 2.0 on 2018-04-16 23:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20180416_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=27)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('rad_lat', models.DecimalField(decimal_places=5, editable=False, max_digits=8)),
                ('rad_long', models.DecimalField(decimal_places=5, editable=False, max_digits=8)),
                ('landmark', models.CharField(max_length=100)),
                ('address_component', django.contrib.postgres.fields.jsonb.JSONField(default=[{'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}, {'long_name': '', 'short_name': '', 'types': []}], verbose_name=django.contrib.postgres.fields.jsonb.JSONField())),
            ],
            options={
                'db_table': 'locations',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
