# Generated by Django 2.0 on 2018-04-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20180417_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=128),
        ),
    ]
