# Generated by Django 2.0 on 2018-04-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20180417_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='location_new',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
