# Generated by Django 2.0 on 2018-04-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20180417_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='clinicians',
            field=models.ManyToManyField(blank=True, null=True, to='api.Clinician'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Location'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialities',
            field=models.ManyToManyField(blank=True, null=True, to='api.Speciality'),
        ),
    ]
