# Generated by Django 2.0 on 2018-04-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20180417_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
    ]
