# Generated by Django 2.0 on 2018-04-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20180419_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'under', 'provider')},
        ),
    ]
