# Generated by Django 2.0 on 2018-04-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20180429_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='healthchecks',
            field=models.ManyToManyField(blank=True, null=True, to='api.HealthCheckup'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
