# Generated by Django 2.0 on 2018-05-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20180429_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Familymember'),
        ),
      
    ]
