# Generated by Django 2.0 on 2018-05-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20180502_1545'),
    ]

    operations = [
    ]
