# Generated by Django 2.0 on 2018-05-04 13:30

import api.models
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20180504_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_added', models.DateTimeField(default=api.models.current_timestamp)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('categories', django.contrib.postgres.fields.hstore.HStoreField(default=api.models.Feedback.get_categories, validators=[django.contrib.postgres.validators.KeysValidator(['doctor', 'clinic_amenities', 'staff_hospitality', 'scheduling'])])),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Clinician')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Seeker')),
            ],
            options={
                'db_table': 'feedbacks',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
