# Generated by Django 2.0 on 2018-05-04 13:41

import api.models
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20180504_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.Feedback.get_categories, validators=[django.contrib.postgres.validators.KeysValidator(['doctor', 'clinic_amenities', 'staff_hospitality', 'scheduling'])]),
        ),
    ]
