# Generated by Django 2.0 on 2018-05-04 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20180504_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='css_class',
            field=models.CharField(choices=[('event-info', 'Info'), ('event-success', 'Success'), ('event-warning', 'Warning'), ('event-special', 'Special'), ('event-danger', 'Danger')], default='event-info', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
