# Generated by Django 2.0 on 2018-05-04 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20180505_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reviewed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
