# Generated by Django 2.0 on 2018-05-07 14:20

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20180507_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='dob',
            field=models.DateField(default=api.models.current_timestamp),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
