# Generated by Django 2.0 on 2018-05-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20180507_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='transactions',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to='api.Transaction'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
