# Generated by Django 2.0 on 2018-05-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20180512_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
    ]
