# Generated by Django 2.0 on 2018-05-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20180512_0710'),
        ('api', '0093_auto_20180510_1843'),
    ]

    operations = [
    ]
