# Generated by Django 2.0 on 2018-05-15 13:06

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_merge_20180515_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckup',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='pre_existing_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Speciality'),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='category_pic',
            field=models.ImageField(default='default_healthcheck.jpg', upload_to='test_categories'),
        ),
        migrations.AlterField(
            model_name='healthcheckup',
            name='age',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(),
        ),
    ]
