# Generated by Django 2.0 on 2018-05-16 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20180515_1836'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='testcategory',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='test_categories'),
        ),
    ]
