# Generated by Django 2.0 on 2018-05-16 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20180516_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('servive_image', models.ImageField(blank=True, null=True, upload_to='amenities')),
            ],
        ),
        
        migrations.AddField(
            model_name='provider',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='api.Amenity'),
        ),
    ]
