# Generated by Django 2.0 on 2018-05-16 11:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20180516_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='amenities',
        ),

    ]
