# Generated by Django 2.0 on 2018-05-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20180516_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='api.Amenity'),
        ),

    ]
