# Generated by Django 2.0 on 2018-05-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20180514_1244'),
        ('api', '0101_auto_20180517_1045'),
    ]

    operations = [
    ]
