# Generated by Django 2.0 on 2018-05-17 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_merge_20180517_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='servive_image',
            new_name='service_image',
        ),
        migrations.AddField(
            model_name='test',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_pic'),
        ),
        migrations.AddField(
            model_name='testsubcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_catagory_pic'),
        ),
       
    ]
