# Generated by Django 2.0 on 2018-05-19 05:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20180518_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnostic_pics')),
            ],
            options={
                'db_table': 'diagnostics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCorporateRecognation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='insurance_pics')),
            ],
            options={
                'db_table': 'insurances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QualityAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quality_pics')),
            ],
            options={
                'db_table': 'quality_accreditations',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='provider',
            name='type',
        ),
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='facility'),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='facility_type'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='no_of_beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceType'),
            preserve_default=False,
        ),
        
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FacilityType'),
        ),
        migrations.RemoveField(
            model_name='provider',
            name='facilities',
        ),
        migrations.AddField(
            model_name='provider',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='api.FacilityType'),
        ),
    ]
